### ISSUE TITLE
IdentityFirstStage + unconditional stage not working

### ISSUE THREAD

**Issue by manurare** [CompVis/stable-diffusion#599]
Hey,

I am trying to run an experiment with `IdentityFirstStage` and `cond_stage_config: __is_unconditional__`. Or in other words the original vanilla diffusion directly in image space. Just train the UNet denoiser without any conditional signal. I am using ImageNet with random crops. However, I get weird samples. They have texture although the content is surely not from the data distribution. Also, they all converge towards a single color prediction. I attach some inputs as well as sample visualizations. Any idea what could be going wrong?

 
![inputs_gs-000800_e-000000_b-000800](https://user-images.githubusercontent.com/43776720/216311936-8ddb678b-c8a9-4ed5-ac35-78fce5014881.png)

![samples_gs-000800_e-000000_b-000800](https://user-images.githubusercontent.com/43776720/216311902-2561c9da-2068-4fa2-a027-b9cac0b554eb.png)

This is my config file:
```
model:
  base_learning_rate: 1.0
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    image_size: 128
    channels: 3
    concat_mode: true
    monitor: val/loss
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: [500, 500, 500, 500, 500]
        cycle_lengths: [2500, 5000, 7500, 10000, 12500]
        f_start: [1e-5, 1e-5, 1e-5, 1e-5, 1e-5]
        f_max: [1e-3, 1e-3, 1e-3, 1e-3, 1e-3]
        f_min: [1e-4, 1e-4, 1e-4, 1e-4, 1e-4]
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 # unused
        in_channels: 3
        out_channels: 3
        model_channels: 32
        attention_resolutions:
        - 8
        - 16
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config: __is_unconditional__


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.imagenet.ImageNetSRTrain
      params:
        size: 128
        degradation: pil_nearest
    validation:
      target: ldm.data.imagenet.ImageNetSRValidation
      params:
        size: 128
        degradation: pil_nearest


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    log_every_n_steps: 10
```
