### ISSUE TITLE
[Question] how to fine-tune the Stable Diffusion Upscaler X4? 

### ISSUE THREAD

**Issue by Estrellama** [CompVis/stable-diffusion#626]
I am seeking information on fine-tuning the Stable Diffusion Upscaler X4. Has anyone knowledge of the training code? If not, would it be possible to provide an explanation of the training method being utilized? I have noted that there is limited information available regarding the training process.

**Comment by andreemic** [comment]
looking for info as well... haven't found much until now other than the [model definition](https://github.com/Stability-AI/stablediffusion/blob/fc1488421a2761937b9d54784194157882cbc3b1/configs/stable-diffusion/x4-upscaling.yaml#L1-L77) and the [gradio script](https://github.com/Stability-AI/stablediffusion/blob/fc1488421a2761937b9d54784194157882cbc3b1/scripts/gradio/superresolution.py#L1-L198)

Maybe we can alter the gradio script to perform training?

**Comment by oubotong** [comment]
Same issue. Looking for some guidance on finetuning 4x upscale model

**Comment by eshaanmoorjani** [comment]
🙏 anybody figure this out yet?

**Comment by KenWuqianghao** [comment]
Any updates?

**Comment by txz32102** [comment]
Hope this helps! 

I am new to diffusion models and have created a [fine-tuning script](https://github.com/txz32102/tmi/blob/main/x4_train_dev.py) based on the [Hugging Face example](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py). This script utilizes an MRI dataset for fine-tuning, which can be found at [txz32102/MRI_512](https://huggingface.co/datasets/txz32102/MRI_512).

To run the script, you can use the following bash command:

```bash
cd /home/data1/musong/workspace/2025/1/1-7/x4_train
/home/data1/musong/envs/main/bin/python3 /home/data1/musong/envs/main/bin/accelerate launch \
    --config_file /home/data1/musong/.cache/huggingface/accelerate/debug.yaml \
    /home/data1/musong/workspace/2025/1/1-7/x4_train/main.py \
    --pretrained_model_name_or_path stabilityai/stable-diffusion-x4-upscaler \
    --output_dir model_x4 \
    --dataset_name txz32102/MRI_512 \
    --resolution=512 \
    --center_crop \
    --random_flip \
    --train_batch_size=1 \
    --gradient_accumulation_steps=1 \
    --gradient_checkpointing \
    --max_train_steps=15000 \
    --learning_rate=1e-05 \
    --max_grad_norm=1 \
    --lr_scheduler=constant \
    --lr_warmup_steps=0
```

Here is the configuration file used in the training setup:

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 6,7
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 29502
```

I've been using 2 * NVIDIA RTX 4090 for this project.
Each GPU uses approximately 13GB of memory during training.

**Comment by txz32102** [comment]
Hope this helps! 

I am new to diffusion models and have created a fine-tuning script based on the [Hugging Face example](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py). This script utilizes an MRI dataset for fine-tuning, which can be found at [txz32102/MRI_512](https://huggingface.co/datasets/txz32102/MRI_512).

To run the script, you can use the following bash command:

```bash
cd /home/data1/musong/workspace/2025/1/1-7/x4_train
/home/data1/musong/envs/main/bin/python3 /home/data1/musong/envs/main/bin/accelerate launch \
    --config_file /home/data1/musong/.cache/huggingface/accelerate/d
[x4_train_dev.txt](https://github.com/user-attachments/files/18360378/x4_train_dev.txt)
ebug.yaml \
    /home/data1/musong/workspace/2025/1/1-7/x4_train/main.py \
    --pretrained_model_name_or_path stabilityai/stable-diffusion-x4-upscaler \
    --output_dir model_x4 \
    --dataset_name txz32102/MRI_512 \
    --resolution=512 \
    --center_crop \
    --random_flip \
    --train_batch_size=1 \
    --gradient_accumulation_steps=1 \
    --gradient_checkpointing \
    --max_train_steps=15000 \
    --learning_rate=1e-05 \
    --max_grad_norm=1 \
    --lr_scheduler=constant \
    --lr_warmup_steps=0
```

Here is the `dev.yaml` used in the training setup:

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 6,7
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 29502
```

I've been using 2 * NVIDIA RTX 4090 for this project.
Each GPU uses approximately 13GB of memory during training.

you should rename `.txt` to `.py` (`.py` file is not allowed, lol)
[x4_train_dev.txt](https://github.com/user-attachments/files/18360385/x4_train_dev.txt)
